# Generated by Django 3.0.7 on 2020-09-22 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_relationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='friend',
            new_name='friends',
        ),
    ]
